<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
  <xacro:property name="safety_offset" value="0.02"/>

  <xacro:include filename="$(find schunk_description)/urdf/common.xacro" />
  <xacro:include filename="$(find schunk_description)/urdf/lwa4p/lwa4p.gazebo.xacro" />
  <xacro:include filename="$(find schunk_description)/urdf/lwa4p/lwa4p.transmission.xacro" />

  <xacro:macro name="schunk_lwa4p" params="parent name *origin has_podest">

    <xacro:if value="${has_podest}">
      <!-- joint between base_link and lwa4p_extended_connector_link -->
      <joint name="${name}_podest_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_podest_link"/>
      </joint>
      <link name="${name}_podest_link">
        <xacro:default_inertial/>
        <visual>
          <origin xyz="0 0 0" rpy="0 ${M_PI} 0" />
          <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_base_link.stl" />
          </geometry>
        </visual>

        <collision>
          <origin xyz="0 0 0" rpy="0 ${M_PI} 0" />
          <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_base_link.stl" />
          </geometry>
        </collision>
      </link>

      <joint name="${name}_base_joint" type="fixed">
        <origin xyz="0 0 0.10" rpy="0 0 0" />
        <parent link="${name}_podest_link"/>
        <child link="${name}_base_link"/>
      </joint>
    </xacro:if>

    <xacro:unless value="${has_podest}">
      <!-- joint between base_link and lwa4p_extended_connector_link -->
      <joint name="${name}_base_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_base_link"/>
      </joint>
    </xacro:unless>

    <link name="${name}_base_link">
      <xacro:default_inertial/>
    </link>

    <!-- joint between arm_0_link and arm_link_1 -->
    <joint name="${name}_joint_1" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${name}_base_link"/>
      <child link="${name}_link_1"/>
      <axis xyz="0 0 1"/>
      <limit effort="370" velocity="1.26" lower="${-2.967 + safety_offset}" upper="${2.967 - safety_offset}"/>
      <!--safety_controller k_position="20" k_velocity="50" soft_lower_limit="${-6.28 + 0.01}" soft_upper_limit="${6.28 - 0.01}" /-->
    </joint>

    <link name="${name}_link_1">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.29364"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_1.stl" />
        </geometry>
        <material name="Schunk/Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_1.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_link_1 and arm_link_2 -->
    <joint name="${name}_joint_2" type="revolute">
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <parent link="${name}_link_1"/>
      <child link="${name}_link_2"/>
      <axis xyz="0 0 1"/>
      <limit effort="370" velocity="1.26" lower="${-2.967 + safety_offset}" upper="${2.967 - safety_offset}"/>
      <!--safety_controller k_position="20" k_velocity="50" soft_lower_limit="${-2.09 + 0.01}" soft_upper_limit="${2.09 - 0.01}" /-->
    </joint>

    <link name="${name}_link_2">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.68311"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_2.stl" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_2.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_link_2 and arm_link_3 -->
    <joint name="${name}_joint_3" type="revolute">
      <origin xyz="0 0.350 0" rpy="0 3.14159 0"/>
      <parent link="${name}_link_2"/>
      <child link="${name}_link_3"/>
      <axis xyz="0 0 1"/>
      <limit effort="176" velocity="1.26" lower="${-2.714 + safety_offset}" upper="${2.714 - safety_offset}"/>
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-6.28 + 0.01}" soft_upper_limit="${6.28 - 0.01}" /-->
    </joint>

    <link name="${name}_link_3">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.1"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_3.stl" />
        </geometry>
        <material name="Schunk/Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_3.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_link_3 and arm_link_4 -->
    <joint name="${name}_joint_4" type="revolute">
      <origin xyz="0 0 0" rpy="-1.5708 3.14159 0" />
      <parent link="${name}_link_3"/>
      <child link="${name}_link_4"/>
      <axis xyz="0 0 1" />
      <limit effort="176" velocity="1.26" lower="${-2.967 + safety_offset}" upper="${2.967 - safety_offset}"/>
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.09 + 0.01}" soft_upper_limit="${2.09 - 0.01}" /-->
    </joint>

    <link name="${name}_link_4">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.68311"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_4.stl" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_4.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_link_4 and arm_link_5 -->
    <joint name="${name}_joint_5" type="revolute">
      <origin xyz="0 0.005263 0.305" rpy="1.5708 0 3.14159" />
      <parent link="${name}_link_4"/>
      <child link="${name}_link_5"/>
      <axis xyz="0 0 1" />
      <limit effort="41.6" velocity="1.26" lower="${-2.967 + safety_offset}" upper="${2.967 - safety_offset}" />
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-6.28 + 0.01}" soft_upper_limit="${6.28 - 0.01}" /-->
    </joint>

    <link name="${name}_link_5">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.807"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_5.stl" />
        </geometry>
        <material name="Schunk/Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_5.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_link_5 and arm_link_6 -->
    <joint name="${name}_joint_6" type="revolute">
      <origin xyz="0 0 0" rpy="-1.5708 0 0" />
      <parent link="${name}_link_5"/>
      <child link="${name}_link_6"/>
      <axis xyz="0 0 1" />
      <limit effort="20.1" velocity="1.26" lower="${-2.967 + safety_offset}" upper="${2.967 - safety_offset}" />
      <!--safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.09 + 0.01}" soft_upper_limit="${2.09 - 0.01}" /-->
    </joint>

    <link name="${name}_link_6">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.819"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_6.stl" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4p/arm_link_6.stl" />
        </geometry>
      </collision>
    </link>


    <!-- extensions -->
    <xacro:schunk_lwa4p_gazebo name="${name}" />
    <xacro:schunk_lwa4p_transmission name="${name}" />

  </xacro:macro>

</robot>
